### ISSUE TITLE
Crashes with various mods

### ISSUE THREAD

**Issue by LukaPix** [Lyeoj/TerraFirmaThings#1]
The current Version 6.0
Crashes with Magneticraft and OCDevices
https://www.curseforge.com/minecraft/mc-mods/ocdevices
https://www.curseforge.com/minecraft/mc-mods/magneticraft

Both mods crash with some itemCapability errors.
Here's the Magneticraft one, but OCDevices seems to crash because of the same reason.
[crash-2020-06-15_17.14.16-client.txt](https://github.com/Lyeoj/TerraFirmaThings/files/4781255/crash-2020-06-15_17.14.16-client.txt)

**Comment by Lyeoj** [comment]
Issue hopefully fixed with release 0.6.1.
