### ISSUE TITLE
Suggestion: Make Gem Display output comparator signal

### ISSUE THREAD

**Issue by Fr4gtastic** [Lyeoj/TerraFirmaThings#11]
A Gem Display could output signal for a comparator, based on how many gems it contains, maybe max power signal if it's full and no signal if it's empty. It could allow for some cool Indiana Jones style traps and hidden rooms.

**Comment by Lyeoj** [comment]
A cool idea, I will look into it!

**Comment by Lyeoj** [comment]
Implemented in release 1.0.1

**Comment by Fr4gtastic** [comment]
Awesome, thank you!
