### ISSUE TITLE
Honing Steel in hand

### ISSUE THREAD

**Issue by Inqie** [Lyeoj/TerraFirmaThings#3]
Less bug, more suggestion:

In third person the honing steel is being held in the hand as though it's an item like an apple, rather than a tool. It looks strange because nothings actually touching the player's hand.

I'd suggest changing it to the way other tools (such as a pickaxe) are held.

**Comment by Lyeoj** [comment]
Good call, this is a very easy thing to change and it does look better that way! Should be fixed in the next release!

**Comment by Lyeoj** [comment]
Addressed in Release 0.8.0
