### ISSUE TITLE
Honing Steel Grit

### ISSUE THREAD

**Issue by Inqie** [Lyeoj/TerraFirmaThings#4]
Just a small issue,
Honing Steel can't be remelted or similar. I noticed because I didn't realise you had to weld it with diamond grit *before* combining it with a stick, so ended up wasting that Black Steel.

Would suggest either changing it from a welding recipe to something else so it can be gritted after-the-fact, or (somehow) allow smelting it back into molten metal like other TFC tools, in case you make it without grit accidentally.

**Comment by Lyeoj** [comment]
This is a fair issue to bring up. I ended up neglecting to give the full honing steel melting capabilities. I will implement it so you can melt down a full honing steel into black steel, and also give a full honing steel the ability to be welded to diamond grit itself (but only if its durability is full)

**Comment by Lyeoj** [comment]
Addressed in Release 0.8.0
