### ISSUE TITLE
Prosp. Hammer with Tool Rack

### ISSUE THREAD

**Issue by Inqie** [Lyeoj/TerraFirmaThings#5]
Aaa! Sorry! It's me again!
Just noticed an inconsistency that the Prospector's Hammer can't be hung on a tool rack like the other tools. That's all!

**Comment by Lyeoj** [comment]
Hello, this issue is due to TFC lacking the ability to designate external items as capable of being placed on a tool rack. The TFC devs will be adding support for it in the next release, so I will be able to fix the issue once that happens.

**Comment by Lyeoj** [comment]
Fixed in release 0.8.2
