### ISSUE TITLE
[SUGGESTION] Can you make it so that shift clicking with a prospector's hammer gives you the 3 layers of stones in a chunk?

### ISSUE THREAD

**Issue by Lumintorious** [Lyeoj/TerraFirmaThings#6]

**Comment by Lyeoj** [comment]
A neat idea! Might consider implementing something like this. I think it might be cool to tie this functioning to the prospecting skill so the higher the skill, the deeper layers you can check.

**Comment by Lyeoj** [comment]
Suggestion has been implemented with release 0.10.0. This check simply picks a set of blocks below the clicked block and checks more blocks below with a higher prospecting skill. This check can show up to 3 rock types at a time and also drains 20 durability from the tool.
