### ISSUE TITLE
[Suggestion] Move flavor text/tooltip for the Sling and Reinforced Sling to translation keys, and give them separate translation keys

### ISSUE THREAD

**Issue by chexo3** [Lyeoj/TerraFirmaThings#9]
This will make translation easier for you in the future, of course, but mainly I want to change it so that the reinforced sling's flavor text completes the phrase started with the regular sling. 

So the tooltips would read `The bigger they are...` and `...the harder they fall` for the regular and reinforced sling respectively. 

I was trying to figure out how I could write this myself and make it a PR, but unfortunately I am still very new to Java and modding modern Minecraft versions, so I couldn't quite figure it out. I will attempt to take another look at this later when I have more time, I might be able to make this a PR after all.

**Comment by Lyeoj** [comment]
The translation key suggestion is valid, I can include that in the next version. I also like the idea of completing the text with the reinforced sling so I can add that in as well. Thanks!

**Comment by Lyeoj** [comment]
Implemented in release 1.0.1
